### ISSUE TITLE
Generating one scan-line per second

### ISSUE THREAD

**Issue by michbus** [4ndries/ADSEE-2-Group-Assignment-for-Spacecraft-and-Aircraft#1]
The generated data rate is calculating the number of pixels per scan-line, assuming one line per second being scanned. The orbital velocity has to be incorporated to calculate how many lines are scanned and transmitted per second

**Comment by eckp** [comment]
Added the calculation and fixed the erroneous calculations with [this commit](https://github.com/4ndries/ADSEE-2-Group-Assignment-for-Spacecraft-and-Aircraft/commit/6e431041c2dc1e8fb9749de4a2739b15cf14b48f#diff-0978cd0d2a59acbc551a384e4f639985).
